# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'ed9f24040f5022c12d434dd1413432fc'
  config.secret_key = 'abc390060a9cded9516ced2a67c81ba3'
  config.default_from = 'charles@thehackingproject.org'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
